# Generated by Django 5.2 on 2025-04-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='courses/')),
                ('start_date', models.DateField()),
                ('duration', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=50)),
            ],
        ),
    ]
