# Generated by Django 5.2 on 2025-05-05 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_course_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
